// @vitest-environment jsdom
/*
================================================================================
FILE: frontend/src/docs-export.test.ts
================================================================================

SUMMARY
    Exercises the standalone documentation viewer, backend/app/docs_assets/
    graph.js, in jsdom. That file ships verbatim inside every documentation zip
    and never runs through the frontend build, so this reads its source, sets up
    the DOM and stubs it expects, and runs it — the closest a unit test gets to
    "open index.html". Covers the node-click navigation the whole feature turns
    on (AC-12) and that the reduced-motion / large-graph paths run without a
    settle and without throwing (AC-19/AC-24).

BASIC IDEA
    graph.js is an IIFE that reads an inline #graph-data script, lays the graph
    out on a <canvas>, and scrolls to a term's section when its node is clicked.
    jsdom has no canvas 2D context, no matchMedia, no ResizeObserver and no
    scrollIntoView, so each is stubbed to the minimum the viewer touches. The
    canvas-drawn output cannot be asserted in jsdom — that is what the browser
    verification in the spec is for — so the assertions here are on observable
    DOM effects: the scroll target and the tooltip element the viewer appends.

    The legend, the canvas accessible label and the "instance data not shown"
    line are generated by the Python side and asserted in
    backend/tests/test_docs_export.py, where the produced HTML is available;
    they are not re-tested here.
================================================================================
*/

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
// graph.js ships verbatim inside every documentation zip and never enters the
// frontend module graph; Vite's ?raw hands over its exact source, the same way
// AboutPanel.test.tsx reads the repository LICENSE. server.fs.allow: [".."] in
// vite.config.ts is what lets this reach outside the frontend root.
import GRAPH_JS from "../../backend/app/docs_assets/graph.js?raw";

/** A no-op 2D context: the viewer calls a dozen canvas methods for their side
 *  effect on pixels, which jsdom does not have. Every method is a stub and every
 *  assignable property is accepted. */
function fakeContext(): CanvasRenderingContext2D {
  const ctx: Record<string, unknown> = {};
  for (const method of [
    "setTransform", "clearRect", "beginPath", "moveTo", "lineTo",
    "stroke", "arc", "fill", "fillText",
  ]) {
    ctx[method] = () => {};
  }
  return ctx as unknown as CanvasRenderingContext2D;
}

/** reduced can be flipped per test before the viewer reads matchMedia. */
let reduced = false;

function setupDom(data: unknown, extraHtml = "") {
  document.body.innerHTML = `
    <figure id="graph-figure">
      <div id="graph-canvas-wrap"><canvas id="graph-canvas"></canvas></div>
    </figure>
    ${extraHtml}
    <script id="graph-data" type="application/json">${JSON.stringify(data)}</script>
  `;
  const canvas = document.getElementById("graph-canvas") as HTMLCanvasElement;
  canvas.getContext = (() => fakeContext()) as unknown as HTMLCanvasElement["getContext"];
  (canvas as unknown as { setPointerCapture: () => void }).setPointerCapture = () => {};
}

function runViewer() {
  // eslint-disable-next-line @typescript-eslint/no-implied-eval
  new Function(GRAPH_JS)();
}

function pointer(type: string, x: number, y: number) {
  const canvas = document.getElementById("graph-canvas")!;
  const ev = Object.assign(new Event(type, { bubbles: true }), {
    clientX: x,
    clientY: y,
    pointerId: 1,
  });
  canvas.dispatchEvent(ev);
}

beforeEach(() => {
  reduced = false;
  window.matchMedia = ((query: string) =>
    ({
      matches: query.includes("reduced-motion") ? reduced : false,
      media: query,
      addEventListener: () => {},
      removeEventListener: () => {},
    }) as unknown as MediaQueryList) as typeof window.matchMedia;
  Element.prototype.scrollIntoView = vi.fn();
});

afterEach(() => {
  document.body.innerHTML = "";
});

describe("documentation graph viewer (graph.js)", () => {
  it("the viewer source actually loaded", () => {
    // A ?raw import that silently yields "" would make runViewer() a no-op and
    // every assertion below pass while proving nothing (the focus-visible trap).
    expect(GRAPH_JS).toContain("graph-canvas-wrap");
  });

  it("clicking a node scrolls to its term section", () => {
    // AC-12. One node with an anchor, and a section with that id. A press with
    // no drag between down and up navigates to the section.
    setupDom(
      {
        nodes: [{ id: "a", label: "A", kind: "class", degree: 0, anchor: "term-a" }],
        edges: [],
        interactiveMaxNodes: 800,
      },
      '<section id="term-a">A</section>',
    );
    runViewer();

    // A single node is fitted to the centre of the (jsdom-sized 800×460) canvas.
    pointer("pointerdown", 400, 230);
    pointer("pointerup", 400, 230);

    expect(document.getElementById("term-a")!.scrollIntoView).toHaveBeenCalled();
  });

  it("a node with no anchor does not navigate", () => {
    setupDom({
      nodes: [{ id: "a", label: "A", kind: "class", degree: 0, anchor: null }],
      edges: [],
      interactiveMaxNodes: 800,
    });
    runViewer();
    pointer("pointerdown", 400, 230);
    pointer("pointerup", 400, 230);
    // Nothing to scroll to; the shared scrollIntoView stub was never called.
    expect(Element.prototype.scrollIntoView).not.toHaveBeenCalled();
  });

  it("renders under reduced motion without a settle and without throwing", () => {
    // AC-24. The reader asked for reduced motion; the viewer skips the force
    // simulation and draws the static placement. Observable proof it ran: the
    // tooltip element it appends to the wrap.
    reduced = true;
    setupDom({
      nodes: [
        { id: "a", label: "A", kind: "class", degree: 1, anchor: null },
        { id: "b", label: "B", kind: "class", degree: 1, anchor: null },
      ],
      edges: [{ source: "a", target: "b", kind: "subClassOf", label: "" }],
      interactiveMaxNodes: 800,
    });
    expect(() => runViewer()).not.toThrow();
    expect(document.querySelector("#graph-canvas-wrap .graph-tooltip")).not.toBeNull();
  });

  it("above the interactive ceiling it renders statically without freezing", () => {
    // AC-19. More nodes than the ceiling: the O(n^2) settle is skipped, so this
    // returns immediately rather than hanging, and still draws.
    const nodes = Array.from({ length: 40 }, (_, i) => ({
      id: `n${i}`,
      label: `N${i}`,
      kind: "class",
      degree: 0,
      anchor: null,
    }));
    setupDom({ nodes, edges: [], interactiveMaxNodes: 5 });
    expect(() => runViewer()).not.toThrow();
    expect(document.querySelector("#graph-canvas-wrap .graph-tooltip")).not.toBeNull();
  });
});
